require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - bin/*
    - vendor/bundle/**/*

Style/Documentation:
  Enabled: false

# rswag workaround
RSpec:
  Language:
    ExampleGroups:
      Regular:
        - path
        - response
        - get
        - post
        - patch
        - put
        - delete
        - head
        - options
        - trace
    Examples:
      Regular:
        - run_test!

RSpec/NestedGroups:
  AllowedGroups:
    - path

RSpec/VariableName:
  AllowedPatterns:
    - ^Authorization$
