require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - bin/*
    - vendor/bundle/**/*

Style/Documentation:
  Enabled: false
