version: "3.9"

volumes:
  db-volume:
  redis-volume:

services:
  app:
    build: ./
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - QUIZ_DATABASE_HOST=db
      - QUIZ_DATABASE_PASSWORD=postgres
      - QUIZ_DATABASE_PORT=5432
      - QUIZ_DATABASE_USERNAME=postgres
      - REDIS_URL=redis://redis:6379/1

  db:
    image: postgres:15.3-alpine3.18
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - db-volume:/var/lib/postgresql/data

  redis:
    image: redis:7.0.12-alpine3.18
    volumes:
      - redis-volume:/usr/local/etc/redis
    ports:
      - "6379:6379"
