---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/alternatives/{id}":
    get:
      summary: Retrieves an alternative
      tags:
      - Alternatives
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: alternative found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Alternative"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnauthorizedError"
        '404':
          description: alternative not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/RecordNotFoundError"
  "/answers":
    get:
      summary: Retrieves answer list
      tags:
      - Answers
      responses:
        '200':
          description: answer found
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Answer"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnauthorizedError"
    post:
      summary: Creates an answer
      tags:
      - Answers
      parameters: []
      responses:
        '201':
          description: answer created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Answer"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnauthorizedError"
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/AnswerError"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Answer"
  "/answers/{id}":
    get:
      summary: Retrieves an answer
      tags:
      - Answers
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: answer found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Answer"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnauthorizedError"
        '404':
          description: answer not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/RecordNotFoundError"
    delete:
      summary: Deletes an answer
      tags:
      - Answers
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: answer deleted
        '401':
          description: unauthorized
        '404':
          description: answer not found
  "/disciplines":
    get:
      summary: Retrieves discipline list
      tags:
      - Disciplines
      responses:
        '200':
          description: discipline found
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Discipline"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnauthorizedError"
    post:
      summary: Creates a discipline
      tags:
      - Disciplines
      parameters: []
      responses:
        '201':
          description: discipline created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Discipline"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnauthorizedError"
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/DisciplineError"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Discipline"
  "/disciplines/{id}":
    get:
      summary: Retrieves a discipline
      tags:
      - Disciplines
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: discipline found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Discipline"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnauthorizedError"
        '404':
          description: discipline not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/RecordNotFoundError"
    patch:
      summary: Updates a discipline
      tags:
      - Disciplines
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: discipline updated
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Discipline"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnauthorizedError"
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/DisciplineError"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Discipline"
    delete:
      summary: Deletes a discipline
      tags:
      - Disciplines
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: discipline deleted
        '401':
          description: unauthorized
        '404':
          description: discipline not found
  "/most_answered/disciplines":
    get:
      summary: Retrieves most answered discipline list
      tags:
      - Most Answered
      responses:
        '200':
          description: most answered found
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/MostAnswered/Discipline"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnauthorizedError"
  "/questions":
    get:
      summary: Retrieves question list
      tags:
      - Questions
      parameters:
      - name: by_topic_id
        in: query
        format: uuid
        required: false
        schema:
          type: string
      - name: by_enunciation_like
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: question found
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Question"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnauthorizedError"
    post:
      summary: Creates a question
      tags:
      - Questions
      parameters: []
      responses:
        '201':
          description: question created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Question"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnauthorizedError"
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/QuestionError"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Question"
  "/questions/{id}":
    get:
      summary: Retrieves a question
      tags:
      - Questions
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: question found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Question"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnauthorizedError"
        '404':
          description: question not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/RecordNotFoundError"
    patch:
      summary: Updates a question
      tags:
      - Questions
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: question updated
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Question"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnauthorizedError"
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/QuestionError"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Question"
    delete:
      summary: Deletes a question
      tags:
      - Questions
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: question deleted
        '401':
          description: unauthorized
        '404':
          description: question not found
  "/topics":
    get:
      summary: Retrieves topic list
      tags:
      - Topics
      responses:
        '200':
          description: topic found
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Topic"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnauthorizedError"
    post:
      summary: Creates a topic
      tags:
      - Topics
      parameters: []
      responses:
        '201':
          description: topic created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Topic"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnauthorizedError"
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TopicError"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Topic"
  "/topics/{id}":
    get:
      summary: Retrieves a topic
      tags:
      - Topics
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: topic found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Topic"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnauthorizedError"
        '404':
          description: topic not found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/RecordNotFoundError"
    patch:
      summary: Updates a topic
      tags:
      - Topics
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: topic updated
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Topic"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UnauthorizedError"
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/TopicError"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Topic"
    delete:
      summary: Deletes a topic
      tags:
      - Topics
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: topic deleted
        '401':
          description: unauthorized
        '404':
          description: topic not found
security:
- bearerAuth: []
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UnauthorizedError:
      type: object
      properties:
        message:
          type: string
      required:
      - message
    RecordNotFoundError:
      type: object
      properties:
        message:
          type: string
      required:
      - message
    Alternative:
      type: object
      properties:
        id:
          type: string
          format: uuid
        description:
          type: string
        correct:
          type: boolean
        question_id:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - id
      - description
      - question_id
      - correct
      - created_at
      - updated_at
    AlternativeError:
      type: object
      properties:
        description:
          type: array
          items:
            type: string
        correct:
          type: array
          items:
            type: string
        question:
          type: array
          items:
            type: string
    Answer:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        user_id:
          type: string
          format: uuid
          readOnly: true
        alternative_id:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        url:
          type: string
          format: url
          readOnly: true
      required:
      - id
      - user_id
      - alternative_id
      - created_at
      - updated_at
      - url
    AnswerError:
      type: object
      properties:
        alternative_id:
          type: array
          items:
            type: string
    Discipline:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        url:
          type: string
          format: url
          readOnly: true
      required:
      - id
      - name
      - created_at
      - updated_at
      - url
    DisciplineError:
      type: object
      properties:
        name:
          type: array
          items:
            type: string
    MostAnswered/Discipline:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        answers_count:
          type: integer
    Question:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        enunciation:
          type: string
        topic_id:
          type: string
          format: uuid
        alternatives_attributes:
          type: array
          items:
            "$ref": "#/components/schemas/Alternative"
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        url:
          type: string
          format: url
          readOnly: true
      required:
      - id
      - enunciation
      - created_at
      - updated_at
      - url
    QuestionError:
      type: object
      properties:
        enunciation:
          type: array
          items:
            type: string
        topic:
          type: array
          items:
            type: string
        alternatives:
          type: array
          items:
            type: string
        alternatives.description:
          type: array
          items:
            type: string
        alternatives.correct:
          type: array
          items:
            type: string
    Topic:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
        discipline_id:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        url:
          type: string
          format: url
          readOnly: true
      required:
      - id
      - name
      - created_at
      - updated_at
      - url
    TopicError:
      type: object
      properties:
        name:
          type: array
          items:
            type: string
        discipline:
          type: array
          items:
            type: string
